gmacario/easy-build

build-yocto-fsl-arm/run.sh

Also add verbosity when restarting container

Standardize on SHAREDDIR=$PWD/shared

---

build-openwrt/.gitignore
build-openwrt/Dockerfile
build-openwrt/build.local/README.md

First attempt at fixing https://github.com/gmacario/easy-build/issues/91

Add build.local/ to container

---

build-openwrt/Dockerfile

That should fix https://github.com/gmacario/easy-build/issues/94

Install package libxml-parser-perl

---

build-openwrt/README.md

That should fix https://github.com/gmacario/easy-build/issues/90

build-openwrt: Add README.md

---

build-yocto/prepend-timestamp.sh

Credits to some clever guys
at http://stackoverflow.com/questions/21564/is-there-a-unix-utility-to-prepend-timestamps-to-lines-of-text

Add script to timestamp BitBake build

---

README.md

Put all badges on one line

---

tools/bblog-to-csv.sh

Get rid of obsolete code (already commented out)

tools: Cleanup bblog-to-csv.sh

---

tools/bblog-analyze.sh

Rename script as it already does more than just creating a .CSV file
Fix https://github.com/gmacario/easy-build/issues/122

tools: Rename script bblog-to-csv.sh to bblog-analyze.sh

---

tools/bblog-analyze.sh

Fix issue https://github.com/gmacario/easy-build/issues/126

Correct argument parsing

---

tools/README.md

tools: Add README.md

---

tools/README.md
tools/run-bblog-analysis.sh

That should fix https://github.com/gmacario/easy-build/issues/123

tools: Add script run-bblog-analysis.sh

---

tools/bblog-analyze.sh

Adopt the same format that MS Excel 2010 uses when saving
a worksheet as CSV (Comma Separated Value)

Improve the format of the generated .CSV file

---

tools/bblog-analyze.sh

Fixes https://github.com/gmacario/easy-build/issues/134

Add column headers in generated .CSV file

---

build-yocto-genivi/README.md
build-yocto-genivi/configure_build.sh

Fix https://github.com/gmacario/easy-build/issues/115

Configure for meta-ivi 7.0.3

---

build-yocto-genivi/create_standalone_images.sh

Fix https://github.com/gmacario/easy-build/issues/145

Make sure that KERNEL file is accessible

---

build-yocto-genivi/README.md

Wrap long lines

---

build-yocto-genivi/README.md
build-yocto-genivi/configure_build.sh

Configure for meta-ivi 8.0 (J-0.1)

---

build-yocto-genivi/create_standalone_images.sh

Fix https://github.com/gmacario/easy-build/issues/147

Check that ROOTFS file exists

---

build-yocto-genivi/configure_build_gdp.sh

Replace 'git fetch' with 'git pull'

---

build-yocto-genivi/run_gdp_qemu.sh

First attempt at running GDP inside QEMU

---

build-yocto-genivi/run_gdp_qemu.sh

See latest changes to instructions posted at
http://wiki.projects.genivi.org/index.php/Hardware_Setup_and_Software_Installation/qemux86-64

Use runqemu from meta-genivi-demo/scripts

---

build-yocto-genivi/README.md

README.md: Add section: Building the GENIVI Demo Platform image

---

build-aosp/Dockerfile

Fix https://github.com/gmacario/easy-build/issues/175

Move the "-y" switch in "RUN apt-get" before "install"

---

build-aosp/.gitignore

Fix https://github.com/gmacario/easy-build/issues/180

build-aosp: Add .gitignore

---

build-yocto-genivi/README.md
build-yocto-genivi/configure_build.sh

See http://lists.genivi.org/pipermail/genivi-meta-ivi/2015-October/000637.html

Configure for YGB 9.0.0 (K-1.0)

---

build-yocto-genivi/README.md

Fix issue https://github.com/gmacario/easy-build/issues/191

README.md: Add ImageLayers.io badge

---

build-yocto/README.md

This is aimed at fixing issue https://github.com/gmacario/easy-build/issues/188

Add ImageLayers.io badge

---

.dockerignore
Dockerfile
experimental/build-inside-jenkins-slave/Dockerfile
experimental/build-inside-jenkins-slave/README.md
experimental/build-inside-jenkins-slave/jenkins-slave

Fix https://github.com/gmacario/easy-build/issues/195

Add baseimage implementing a Jenkins Slave

---

build-yocto-genivi/Dockerfile

Fix https://github.com/gmacario/easy-build/issues/205

build-yocto-genivi: Fix Docker Hub autobuild failure

---

build-yocto-genivi/Dockerfile
build-yocto-genivi/run-gocd-agent.sh

Add support for implementing a gocd agent

---

experimental/build-yocto-new/Dockerfile

Fix issue https://github.com/gmacario/easy-build/issues/211

Dockerfile: Create a non-root user "build"

---

build-yocto-genivi/Dockerfile
build-yocto-genivi/clone-and-build-gdp.sh

See https://at.projects.genivi.org/jira/browse/GDP-92

build-yocto-genivi: Install git-svn

---

build-yocto/Dockerfile

Fix issue https://github.com/gmacario/jenkins-build-agl-distro/issues/5

build-yocto/Dockerfile: Create user "jenkins"

---

build-capi-native/Dockerfile
build-capi-native/build-in-docker.md

Imported from https://github.com/gmacario/common-api-c-poc/tree/feat-build-in-docker/doc

Add subproject: build-capi-native

---

build-yocto/Dockerfile

Fix https://github.com/gmacario/easy-jenkins/issues/79

build-yocto/Dockerfile: Install package `tree`

---

build-aosp/Dockerfile

build-aosp: Dockerfile: Install package lzop

---

build-aosp/Dockerfile

build-aosp/Dockerfile: Install package u-boot-tools

---

build-aosp/Dockerfile

build-aosp: Changes for build_android_udooneo

---

build-yocto-genivi/Dockerfile

build-yocto-genivi: Add package `tree`

---

README.md

Fix Issue https://github.com/gmacario/easy-build/issues/237

Replace ImageLayers badge with MicroBadger

---

.gitignore

Add to .gitignore: .DS_Store

---

README.md

README.md: Fix Gitter badge

---

README.md

README.md: Add CodeTriage badge

---

build-yocto-genivi/Dockerfile

Fix issue https://github.com/gmacario/easy-build/issues/251

build-yocto-genivi: Rebase on newer gocd-agent image

---

build-yocto/Dockerfile

Based on previous PR https://github.com/gmacario/easy-build/pull/261
Thanks @zzeroo for his contribution

build-yocto: Update baseimage to Ubuntu 16.04 (v2)

---

Dockerfile

Fix https://github.com/gmacario/easy-build/issues/268

easy-build: Rebase on ubuntu:18.04

---

build-yocto/Dockerfile

As suggested by @nandk85 in #245
Signed-off-by: Gianpaolo Macario <gianpaolo.macario@solarma.it>

build-yocto: Add DEBIAN_FRONTEND=noninteractive

---

README.md

README.md: Remove waffle.io badge

---

README.md

Update Copyright year

---

codefresh.yml

Add step "BuildingDockerImage_buildyocto"
